# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32da390d21bdeae4261f9381492cf7740ae22dc2eeafdcceae52b2c9456f8b3ceee731201f3953556ad9c7574c4f545b9f88dae3f1b287b859a20a816344b118

test:
  secret_key_base: 4864a9ee8183614d9711b9c6feaf091a0779c446eed933196a75cad840db0ec3108fc5604841f796de5d341c15f17117d32487e8f435117cb28887c33bc692da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
